AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation template to create an S3 bucket with CORS and versioning enabled.

Resources:
  MyS3Bucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: ramya2012-bucket
      VersioningConfiguration:
        Status: Enabled
      CorsConfiguration:
        CorsRules:
          - AllowedHeaders:
              - '*'
            AllowedMethods:
              - GET
            AllowedOrigins:
              - '*'
            ExposedHeaders:
              - Date
            Id: myCORSRuleId1
            MaxAge: 360

Outputs:
  BucketName:
    Value: !Ref MyS3Bucket
    Description: 'Name of the S3 bucket'
